import firebase from 'firebase/app';//makes firebase avilable in the app
import 'firebase/auth';//makes firebase aunthtication features available to this project
import 'firebase/database';//makes firebase database features available to this project

const config = {
    apiKey: "AIzaSyAMzMQ7d9R3VySOCMBqvUncIPtMCQjPWpg",
    authDomain: "react-firebase-authentic-99189.firebaseapp.com",
    databaseURL: "https://react-firebase-authentic-99189.firebaseio.com",
    projectId: "react-firebase-authentic-99189",
    storageBucket: "react-firebase-authentic-99189.appspot.com",
    messagingSenderId: "347141442179"
  };//this configuration is automatically generated by firebase upon making a a firebase project, it connects firebase to my react project

  if (!firebase.apps.length) {
    firebase.initializeApp(config);//app is initialised with the configuration
  }

const db = firebase.database();//function that applies database features to something
const auth = firebase.auth();//function that applies authentication features to something

export {//makes the auth db file available to use by other files
  auth,
  db,
};